version: '3.8'

services:
  # GPU benchmarks service
  gpu-benchmarks:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
      - ./benchmarks:/app/benchmarks
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "run.py", "--help"]

  # CPU benchmarks service
  cpu-benchmarks:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
      - ./benchmarks:/app/benchmarks
    environment:
      - CUDA_VISIBLE_DEVICES=""
    command: ["python", "run.py", "--help"]

  # Interactive shell service for development
  shell:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./results:/app/results
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: ["/bin/bash"]

  # Service to run all benchmarks
  run-all-benchmarks:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash", "run_all_benchmarks.sh"] 